import type { Listing } from '@/types'

const SELLERS = {
  ahmed:  { id: 'sel-001', name: 'Ahmed Mohammed',  nameAr: 'أحمد محمد',  rating: 4.8, phone: '+249912345678' },
  hassan: { id: 'sel-002', name: 'Hassan Ibrahim',  nameAr: 'حسن إبراهيم', rating: 4.9, phone: '+249923456789' },
  fatima: { id: 'sel-003', name: 'Fatima Ahmed',    nameAr: 'فاطمة أحمد',  rating: 4.7, phone: '+249934567890' },
  omar:   { id: 'sel-004', name: 'Omar Salih',      nameAr: 'عمر صالح',    rating: 4.6, phone: '+249945678901' },
}

export const listings: Listing[] = [
  {
    id: 'lst-001',
    title: 'Sorghum — 50 Tons',
    titleAr: 'ذرة رفيعة — ٥٠ طن',
    description: 'High-quality sorghum from Gedaref region, freshly harvested.',
    descriptionAr: 'ذرة رفيعة عالية الجودة من منطقة القضارف، محصولة هذا الموسم.',
    category: 'crops',
    price: 82500, currency: 'SDG', unit: 'ton', quantity: 50,
    location: 'Gedaref', locationAr: 'القضارف',
    seller: SELLERS.ahmed, images: [], status: 'active',
    createdAt: '2026-06-07T08:00:00Z',
  },
  {
    id: 'lst-002',
    title: 'Premium Sesame — 20 Tons',
    titleAr: 'سمسم ممتاز — ٢٠ طن',
    description: 'Export-grade white sesame from Kassala, cleaned and ready for shipment.',
    descriptionAr: 'سمسم أبيض بجودة تصديرية من كسلا، منظف وجاهز للشحن.',
    category: 'crops',
    price: 320000, currency: 'SDG', unit: 'ton', quantity: 20,
    location: 'Kassala', locationAr: 'كسلا',
    seller: SELLERS.hassan, images: [], status: 'active',
    createdAt: '2026-06-08T09:00:00Z',
  },
  {
    id: 'lst-003',
    title: 'John Deere 5M Tractor — For Rent',
    titleAr: 'جرار جون دير ٥م — للإيجار',
    description: '2023 John Deere 5M tractor available for seasonal rental. Driver included.',
    descriptionAr: 'جرار جون دير ٥م موديل ٢٠٢٣ متاح للإيجار الموسمي. يشمل السائق.',
    category: 'equipment',
    price: 15000, currency: 'SDG', unit: 'day', quantity: 1,
    location: 'Khartoum', locationAr: 'الخرطوم',
    seller: SELLERS.fatima, images: [], status: 'active',
    createdAt: '2026-06-06T10:00:00Z',
  },
  {
    id: 'lst-004',
    title: 'Irrigation Water Pump 6"',
    titleAr: 'مضخة مياه للري ٦ بوصة',
    description: 'Heavy-duty diesel irrigation pump, 6-inch outlet, excellent condition.',
    descriptionAr: 'مضخة ري ديزل ثقيلة، منفذ ٦ بوصة، حالة ممتازة.',
    category: 'equipment',
    price: 850000, currency: 'SDG', unit: 'unit', quantity: 2,
    location: 'Gedaref', locationAr: 'القضارف',
    seller: SELLERS.omar, images: [], status: 'active',
    createdAt: '2026-06-05T11:00:00Z',
  },
  {
    id: 'lst-005',
    title: 'Certified Sesame Seeds',
    titleAr: 'بذور سمسم معتمدة',
    description: 'Ministry of Agriculture certified sesame seeds, 92% germination rate.',
    descriptionAr: 'بذور سمسم معتمدة من وزارة الزراعة، نسبة إنبات ٩٢٪.',
    category: 'seeds',
    price: 45000, currency: 'SDG', unit: 'bag (50kg)', quantity: 100,
    location: 'Gezira', locationAr: 'الجزيرة',
    seller: SELLERS.ahmed, images: [], status: 'active',
    createdAt: '2026-06-04T08:30:00Z',
  },
  {
    id: 'lst-006',
    title: 'High-Yield Sorghum Seeds',
    titleAr: 'بذور ذرة عالية الإنتاج',
    description: 'Improved drought-tolerant sorghum variety, suited for semi-arid regions.',
    descriptionAr: 'صنف ذرة محسّن ومتحمل للجفاف، مناسب للمناطق شبه الجافة.',
    category: 'seeds',
    price: 28000, currency: 'SDG', unit: 'bag (25kg)', quantity: 200,
    location: 'El Obeid', locationAr: 'الأبيض',
    seller: SELLERS.hassan, images: [], status: 'active',
    createdAt: '2026-06-03T07:00:00Z',
  },
  {
    id: 'lst-007',
    title: 'DAP Fertilizer — 50kg Bags',
    titleAr: 'سماد DAP — أكياس ٥٠ كغ',
    description: 'Diammonium phosphate (18-46-0), suitable for pre-planting application.',
    descriptionAr: 'فوسفات الأمونيوم الثنائي (18-46-0)، مناسب للتطبيق قبل الزراعة.',
    category: 'fertilizer',
    price: 32000, currency: 'SDG', unit: 'bag (50kg)', quantity: 500,
    location: 'Khartoum', locationAr: 'الخرطوم',
    seller: SELLERS.fatima, images: [], status: 'active',
    createdAt: '2026-06-02T09:00:00Z',
  },
  {
    id: 'lst-008',
    title: 'Urea Fertilizer (46% N)',
    titleAr: 'يوريا (٤٦٪ نيتروجين)',
    description: 'Granular urea, 46% nitrogen content, ideal for top-dressing.',
    descriptionAr: 'يوريا حبيبية، نيتروجين ٤٦٪، مثالية للتسميد السطحي.',
    category: 'fertilizer',
    price: 28500, currency: 'SDG', unit: 'bag (50kg)', quantity: 300,
    location: 'Gedaref', locationAr: 'القضارف',
    seller: SELLERS.omar, images: [], status: 'active',
    createdAt: '2026-06-01T10:00:00Z',
  },
]
